#!/usr/bin/env python3
"""
Generate static/_redirects for Netlify.

Most rules live in netlify.toml, which is easier to read. This file exists for
the ones that have to be enumerated:

**`.wmv` → `.mp4`.** Netlify's splat (`*`) only matches at the end of a pattern,
so `/videos/*.wmv` is not expressible — each clip needs its own line. Twenty
years of forum posts and external links point at the .wmv URLs, and the archive
publishes only the transcoded MP4s, so without these the old links 404.

Run after transcoding; `scripts/build_site.sh` calls it.
"""
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MP4 = ROOT / "static" / "videos"
OUT = ROOT / "static" / "_redirects"

HEADER = """# GENERATED by scripts/gen_redirects.py — do not edit by hand.
# Broader rules (410s, /node → /) are in netlify.toml.

"""


def main():
    lines = [HEADER]

    clips = sorted(MP4.rglob("*.mp4"))
    if clips:
        lines.append(
            "# Archived clips were .wmv until they were transcoded to MP4.\n"
            "# Netlify splats only match at the end of a pattern, so a single\n"
            "# /videos/*.wmv rule is not possible — one line per clip.\n"
        )
        for f in clips:
            rel = f.relative_to(MP4).as_posix()
            wmv = "/videos/" + urllib.parse.quote(rel[:-4] + ".wmv")
            mp4 = "/videos/" + urllib.parse.quote(rel)
            lines.append(f"{wmv}  {mp4}  301\n")
        lines.append("\n")

    lines.append(
        "# Drupal's aggregator and private messages are gone for good.\n"
        "/aggregator/*   /404.html   410\n"
        "/messages/*     /404.html   410\n"
        "/userpoints/*   /404.html   410\n"
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(clips)} clip redirects")
    return 0


if __name__ == "__main__":
    sys.exit(main())
